-   id: circleci-validate
    name: check .circle ci file
    description: Validate all the .yaml files in .circleci dir
    entry: circleci-validate
    language: python
    files: ^.circleci/*.*ml$
    types: [file,yaml]
