-   id: circleci-validate
    name: check .circleci file
    description: Validate all the .yaml files in .circleci dir
    entry: circleci-validate
    language: python
    files: ^.circleci/
    types: [file]
