-   id: circleci-validate
    name: CircleCI config validation
    description: Test if the CircleCI config is well formed.
    entry: circleci-validate
    language: python
    files: ^.circleci/*.*ml$
